# Generated by Django 3.0.7 on 2020-06-20 18:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True),
        ),
    ]
